import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme/ThemeProvider'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/AppSidebar'
import { promptGuidelines } from '@/lib/promptGuidelines'
import { JotaiProvider } from '@/state/JotaiProvider'
import { NavigationBar } from '@/components/NavigationBar'
import { PromptInput } from '@/components/prompt-input'
import { NeedsAuth } from '@/components/NeedsAuth'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className='h-full w-full' lang='en' suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<JotaiProvider>
						<SidebarProvider className='h-full'>
							<AppSidebar promptGuidelines={promptGuidelines} />
							<main className='w-full flex-1 h-full'>
								<NavigationBar />
								{children}
								<NeedsAuth>
									<PromptInput />
								</NeedsAuth>
							</main>
						</SidebarProvider>
					</JotaiProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
